baseURL = "https://erjohnson.github.io"
languageCode = 'en-us'
title = "ej"
theme = "or"
copyright = "Eric Johnson"
defaultContentLanguage = "en"

# rgb(23, 23, 23)
# rgb(242, 241, 236)

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

enableEmoji = true

[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    noClasses = false

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20


